### ISSUE TITLE
Add documentations for Boxes

### ISSUE THREAD

**Issue by dasnebbi** [WoltLab/docs.woltlab.com#28]
Except the [Box Package PIP](https://docs.woltlab.com/package_pip_box.html) there is no documentation regarding boxes. Would be nice to add something to the PHP API-section like there already is for [Pages](https://docs.woltlab.com/php_pages.html), so people can get some overview.

Furthermore an extension of the tutorial series would be useful.

**Comment by Gravatronics** [comment]
> Furthermore an extension of the tutorial series would be useful.

Please separate specific issues for the topics that should be covered.
