### ISSUE TITLE
Add documentations for File uploads

### ISSUE THREAD

**Issue by dasnebbi** [WoltLab/docs.woltlab.com#30]
The documentation lacks everything regarding file uploads and how to handle them. 
So.. please add something? ;-)

Theoretical (example for this case, it's absolutely fictional!): I want to let users upload images to /wcf/images/user-uploads/, which are later shown on my page "Pics users want to show". But... how, which classes are needed and so on. After reading the docs I'd still have no clue.

**Comment by ilouHD** [comment]
After testing a lot with file-uploads, I can try to add such an entry. First for single-file-uploads, later for multiple file uploads. I will try that the next weeks, hopefully.

**Comment by joshuaruesweg** [comment]
As a note: We have already a section for uploading files with the form builder: https://docs.woltlab.com/php_api_form_builder-form_fields.html#uploadformfield 

The form builder makes developing forms very easy,  comfortable and flexible, so that is what you should use for uploading files in the most cases.

**Comment by ilouHD** [comment]
This is one possibility to upload files.
I thought of using the provided JavaScript-API-Module in `WoltLabSuite/Core/Upload`. As I know you're using it also in the Gallery to upload images.

JavaScript might cover the remaining cases to upload files, as this provides some possibilites, the "normal" file upload can't.

**Comment by joshuaruesweg** [comment]
The form field uses internally JavaScript to handle the upload. It is not the HTML `file`-Input. For example, it is used to handle the image upload with the reaction type add form.
